name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches-ignore: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.25.0'

    - name: Build
      run: ./tools/build.sh

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.25.0'

    - name: Test
      run: go test -race ./...

    - name: Sub command Test
      run: $GITHUB_WORKSPACE/tools/sub-command-test.sh

  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.25.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: v2.4.0
          verify: false
          # This linter works based on the file modification when running under github actions because it's
          # not given full access to the git history and therefore gets the wrong date for all files.
          args: --disable goheader

  fieldalignment:
    name: fieldalignment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.25.0'

      - name: install fieldalignment
        run: go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest

      - name: check for diff
        run: $GITHUB_WORKSPACE/tools/fieldalignment-lint.sh
