name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches-ignore: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: 'stable'

    - name: Build
      run: ./tools/build.sh

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: 'stable'

    - name: Test
      run: go test -race ./...

  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: 'stable'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: v2.4.0
          verify: false
          # This linter works based on the file modification when running under github actions because it's
          # not given full access to the git history and therefore gets the wrong date for all files.
          args: --disable goheader